### ISSUE TITLE
Allow browser apps to be resized by title filters

### ISSUE THREAD

**Issue by boarder2** [BarRaider/streamdeck-windowsmover#1]
With the current implementation, all windows belonging to a particular process name will be resized. 

This results in limited functionality when using browser based apps.

Perhaps using something like `EnumDesktopWindows` - https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-enumdesktopwindows and allowing the user to specify a contains string, or regex (maybe too complicated) would allow more options for browser applications.

**Comment by BarRaider** [comment]
v1.8 now supports filtering by the window title. Keep in mind Firefox/Chrome's title changes based on the active tab, but it does work
